### ISSUE TITLE
java.lang.reflect.InaccessibleObjectException when trying to use parseCsv()

### ISSUE THREAD

**Issue by mrtnbm** [kayr/fuzzy-csv#1]
Hello,

## Error
When I try to use the `ParseCsv` function, a `java.lang.reflect.InaccessibleObjectException` is thrown.

## MWE
- Java 11.0.14.1_1 (Openjdk)
- fuzzy-csv version 1.8.0-groovy3 Maven-Config:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.example</groupId>
    <artifactId>example</artifactId>
    <packaging>jar</packaging>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <maven.compiler.source>11</maven.compiler.source>
        <maven.compiler.target>11</maven.compiler.target>
    </properties>

    <build>
        <plugins>
            <plugin>
                <artifactId>maven-assembly-plugin</artifactId>
                <version>3.3.0</version>
                <executions>
                    <execution>
                        <id>make-assembly</id>
                        <phase>package</phase>
                        <goals>
                            <goal>single</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <archive>
                        <manifest>
                            <addClasspath>true</addClasspath>
                            <mainClass>com.example.Main</mainClass>
                        </manifest>
                    </archive>
                    <descriptorRefs>
                        <descriptorRef>jar-with-dependencies</descriptorRef>
                    </descriptorRefs>
                </configuration>
            </plugin>
        </plugins>
    </build>

    <dependencies>
        <dependency>
            <groupId>org.apache.maven</groupId>
            <artifactId>maven-plugin-api</artifactId>
            <version>3.8.5</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.maven.plugin-tools</groupId>
            <artifactId>maven-plugin-annotations</artifactId>
            <version>3.6.4</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>io.github.kayr</groupId>
            <artifactId>fuzzy-csv</artifactId>
            <version>1.8.0-groovy3</version>
        </dependency>
    </dependencies>
</project>
```
```java
import fuzzycsv.FuzzyCSVTable;

public class Main {
        public static void main(String[] args) {
                FuzzyCSVTable table = FuzzyCSVTable.parseCsv("NAME,MIDDLENAME,SURNAME,AGE\n" + "Jason,Noname,Scarry,16");
        }
}
```
        

## Log
```java
java.lang.reflect.InaccessibleObjectException: Unable to make protected void java.lang.Object.finalize() throws java.lang.Throwable accessible: module java.base does not "opens java.lang" to unnamed module @22a67b4
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
        at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:200)
        at java.base/java.lang.reflect.AccessibleObject.setAccessible(AccessibleObject.java:130)
        at org.codehaus.groovy.reflection.CachedClass$3$1.run(CachedClass.java:86)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
        at org.codehaus.groovy.reflection.CachedClass$3.initValue(CachedClass.java:81)
        at org.codehaus.groovy.reflection.CachedClass$3.initValue(CachedClass.java:79)
        at org.codehaus.groovy.util.LazyReference.getLocked(LazyReference.java:46)
        at org.codehaus.groovy.util.LazyReference.get(LazyReference.java:33)
        at org.codehaus.groovy.reflection.CachedClass.getMethods(CachedClass.java:250)
        at org.codehaus.groovy.reflection.CachedClass$3.initValue(CachedClass.java:116)
        at org.codehaus.groovy.reflection.CachedClass$3.initValue(CachedClass.java:79)
        at org.codehaus.groovy.util.LazyReference.getLocked(LazyReference.java:46)
        at org.codehaus.groovy.util.LazyReference.get(LazyReference.java:33)
        at org.codehaus.groovy.reflection.CachedClass.getMethods(CachedClass.java:250)
        at org.codehaus.groovy.reflection.CachedClass$3.initValue(CachedClass.java:116)
        at org.codehaus.groovy.reflection.CachedClass$3.initValue(CachedClass.java:79)
        at org.codehaus.groovy.util.LazyReference.getLocked(LazyReference.java:46)
        at org.codehaus.groovy.util.LazyReference.get(LazyReference.java:33)
        at org.codehaus.groovy.reflection.CachedClass.getMethods(CachedClass.java:250)
        at org.codehaus.groovy.reflection.stdclasses.CachedClosureClass.<init>(CachedClosureClass.java:29)
        at org.codehaus.groovy.reflection.ClassInfo.createCachedClass(ClassInfo.java:312)
        at org.codehaus.groovy.reflection.ClassInfo.access$400(ClassInfo.java:37)
        at org.codehaus.groovy.reflection.ClassInfo$LazyCachedClassRef.initValue(ClassInfo.java:484)
        at org.codehaus.groovy.reflection.ClassInfo$LazyCachedClassRef.initValue(ClassInfo.java:475)
        at org.codehaus.groovy.util.LazyReference.getLocked(LazyReference.java:46)
        at org.codehaus.groovy.util.LazyReference.get(LazyReference.java:33)
        at org.codehaus.groovy.reflection.ClassInfo.getCachedClass(ClassInfo.java:94)
        at org.codehaus.groovy.reflection.ReflectionCache.getCachedClass(ReflectionCache.java:107)
        at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.registerMethods(MetaClassRegistryImpl.java:189)
        at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.<init>(MetaClassRegistryImpl.java:93)
        at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.<init>(MetaClassRegistryImpl.java:71)
        at groovy.lang.GroovySystem.<clinit>(GroovySystem.java:33)
        at org.codehaus.groovy.runtime.InvokerHelper.<clinit>(InvokerHelper.java:61)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.createCallStaticSite(CallSiteArray.java:72)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.createCallSite(CallSiteArray.java:159)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
        at fuzzycsv.FuzzyCSVTable.<clinit>(FuzzyCSVTable.groovy:24)
        at Main.main(Main.java:27)
Exception in thread "main" BUG! UNCAUGHT EXCEPTION: java.lang.invoke.MethodHandles$Lookup.<init>(java.lang.Class,int)
        at org.codehaus.groovy.vmplugin.v7.Java7.<clinit>(Java7.java:43)
        at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
        at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1160)
        at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.ensureClassInitialized(MethodHandleAccessorFactory.java:300)
        at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.newConstructorAccessor(MethodHandleAccessorFactory.java:103)
        at java.base/jdk.internal.reflect.ReflectionFactory.newConstructorAccessor(ReflectionFactory.java:236)
        at java.base/java.lang.reflect.Constructor.acquireConstructorAccessor(Constructor.java:546)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:496)
        at java.base/java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128)
        at java.base/jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:341)
        at java.base/java.lang.Class.newInstance(Class.java:677)
        at org.codehaus.groovy.vmplugin.VMPluginFactory.createPlugin(VMPluginFactory.java:56)
        at org.codehaus.groovy.vmplugin.VMPluginFactory.<clinit>(VMPluginFactory.java:37)
        at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.<init>(MetaClassRegistryImpl.java:99)
        at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.<init>(MetaClassRegistryImpl.java:71)
        at groovy.lang.GroovySystem.<clinit>(GroovySystem.java:33)
        at org.codehaus.groovy.runtime.InvokerHelper.<clinit>(InvokerHelper.java:61)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.createCallStaticSite(CallSiteArray.java:72)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.createCallSite(CallSiteArray.java:159)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
        at fuzzycsv.FuzzyCSVTable.<clinit>(FuzzyCSVTable.groovy:24)
        at Main.main(Main.java:27)
Caused by: java.lang.NoSuchMethodException: java.lang.invoke.MethodHandles$Lookup.<init>(java.lang.Class,int)
        at java.base/java.lang.Class.getConstructor0(Class.java:3617)
        at java.base/java.lang.Class.getDeclaredConstructor(Class.java:2786)
        at org.codehaus.groovy.vmplugin.v7.Java7.<clinit>(Java7.java:41)
        ... 24 more
```

**Comment by kayr** [comment]
Hi @mrtnbm , I some how cannot reproduce your problem.. I tried to reproduce your error but nothing came up using this project..
[fuzzy-maven.zip](https://github.com/kayr/fuzzy-csv/files/8966293/fuzzy-maven.zip)
.

Java Version 11.0.15
Maven 3.8.5

I run the command `mvn clean compile exec:java -Dexec.mainClass=Main` and no error was observed.

**Comment by kayr** [comment]
However when I switched to Java 14.. I reproduced the error..for now I suggest downgrading to Java 11. You should double check your java version.. it looks like a compatibility bug.. 

Reference: https://issues.apache.org/jira/browse/GROOVY-9211

**Comment by mrtnbm** [comment]
Hello @kayr,

thanks for the information. I get the error even with Java 11 and maven 3.8.6, when I run `mvn install` and execute the `jar with java -jar target/example-1.0-SNAPSHOT-jar-with-dependencies.jar`. 
```
Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63)
Maven home: C:\ProgramData\chocolatey\lib\maven\apache-maven-3.8.6
Java version: 11.0.14.1, vendor: Oracle Corporation, runtime: C:\Program Files\OpenJDK\openjdk-11.0.14.1_1
Default locale: de_DE, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"
```

**Comment by kayr** [comment]
What is the output of `java -version`

**Comment by mrtnbm** [comment]
That is apperently wrong (java18), although my env vars are set to java11... I will look for a fix. Thanks for the hint

**Comment by mrtnbm** [comment]
Ok, I fixed it. `java -version` now shows 
```
java -version
openjdk version "11.0.14.1" 2022-02-08
OpenJDK Runtime Environment 18.9 (build 11.0.14.1+1)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.14.1+1, mixed mode)
```
Unfortunately, it still does not work :(

**Comment by kayr** [comment]
Can you post your new output?

**Comment by mrtnbm** [comment]
```
java -jar target/example-1.0-SNAPSHOT-jar-with-dependencies.jar
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.reflection.CachedClass$3$1 (file:/C:/Weblate/tst/demo/target/example-1.0-SNAPSHOT-jar-with-dependencies.jar) to method java.lang.Object.finalize()
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.reflection.CachedClass$3$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```
I already tried to use --illegal-access=permit but that didn't help.

**Comment by kayr** [comment]
ok.. looks like it is actually working... add the print table method to see some output..

![image](https://user-images.githubusercontent.com/1183390/175290309-4f1f7f43-be70-4d09-9df5-b2f594071ff8.png)

**Comment by mrtnbm** [comment]
Ok, thank you very much. I was concentrating so hard on the errors that I forgot to actually print something..

**Comment by kayr** [comment]
No problem :)
